psychology/events/urls.py
from django.urls import path
from events import views


app_name = 'events'

urlpatterns = [
	path('', views.events, name='events'),
	path('id/<int:id>/', views.event, name='event')
]

psychology/pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'

urlpatterns = [
	path('', views.index, name='index'),
	path('oferta/', views.oferta, name='oferta'),
	path('confidentiality/', views.confidentiality, name='confidentiality'),
	path('copyright/', views.copyright, name='copyright'),
	path('representative/', views.representative, name='representative')
]

psychology/psychology/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
    path('events/', include('events.urls', namespace='events')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

psychology/users/urls.py
from django.urls import path
from users.views import (
	views,
	lk_admin,
	lk_expert
)
from django.contrib.auth import views as a_views
from users.forms import (
	YourOwnChangePassForm,
	YourOwnResetPassForm,
	YourOwnSetPassForm
)

app_name = 'users'

urlpatterns = [
	# Авторизация
	path('get_representative/',
		views.get_representative,
		name='get_representative'),
	path('invite/<int:id>/',
		views.invite,
		name='invite'),
	path('reg/<str:link>',
		views.registration,
		name='registration'),
	path('login/',
		views.login_view,
		name='login'),
	path('logout/',
		views.logout_view,
		name='logout'),
	path('password_reset/',
		a_views.PasswordResetView.as_view(
			template_name='users/reset_password_form.html',
			form_class=YourOwnResetPassForm,
			success_url='done',
			email_template_name='emails/password_reset_email.html'),
		name='reset_pass'),
	path('password_reset/done/',
		views.reset_pass_done,
		name='reset_pass_done'),
	path('reset/<uidb64>/<token>/',
		a_views.PasswordResetConfirmView.as_view(
			template_name='users/reset_password_form.html',
			form_class=YourOwnSetPassForm,
			success_url='done/'),
		name='password_reset_confirm'),
	path('reset/<uidb64>/set-password/done/',
		views.pass_confirm_done,
		name='confirm_pass_done'),

	# Личный кабинет администратора
	path('list_representative/',
		lk_admin.list_representative,
		name='list_representative'),

	path('department/add/',
		lk_admin.department_add,
		name='department_add'),
	path('department/edit/<int:id>/',
		lk_admin.department_edit,
		name='department_edit'),
	path('department/delete/<int:id>/',
		lk_admin.department_delete,
		name='department_delete'),
	path('departments/',
		lk_admin.departments,
		name='departments'),

	path('skill/add/',
		lk_admin.skill_add,
		name='skill_add'),
	path('skill/edit/<int:id>/',
		lk_admin.skill_edit,
		name='skill_edit'),
	path('skill/delete/<int:id>/',
		lk_admin.skill_delete,
		name='skill_delete'),
	path('skills/',
		lk_admin.skills,
		name='skills'),
	path('just/',
		lk_admin.just,
		name='just12'),

	# Личный кабинет эксперта
	path('events/',
		lk_expert.events,
		name='events'),
	path('events/add/',
		lk_expert.event_add,
		name='event_add'),
	path('events/edit/<int:id>/',
		lk_expert.event_edit,
		name='event_edit'),
	path('events/delete/<int:id>/',
		lk_expert.event_delete,
		name='event_delete'),

	path('profile/',
		lk_expert.profile,
		name='profile'),
	path('expert_chg_pass/',
		a_views.PasswordChangeView.as_view(
			template_name='users/chg_pass_expert.html',
			form_class=YourOwnChangePassForm,
			success_url='done'),
		name='expert_chg_pass'),
	path('expert_chg_pass/done/',
		lk_expert.success_chg_pass,
		name='success_chg_pass'),

	path('', views.experts, name='experts'),
	path('id/<int:id>/', views.expert, name='expert')
]

psychology/events/models.py
from django.db import models
from django.contrib.auth import get_user_model

from users.models import Department


User = get_user_model()


class Event(models.Model):
	expert = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		related_name='events')
	title = models.CharField(
		verbose_name='Мероприятие',
		help_text='Введите название Вашего мероприятия',
		max_length=255)
	description = models.TextField(
		verbose_name='Вся информация о событии',
		help_text='Введите подробное описание мероприятия, заранее подготовьте текст')
	city = models.ForeignKey(
		Department,
		verbose_name='Город',
		help_text='Выберите город, в котором будет проходить мероприятие',
		on_delete=models.CASCADE,
		related_name='events')
	address = models.CharField(
		verbose_name='Адрес',
		help_text='Введите адрес, где будет проходить мероприятие без указания города',
		max_length=255)
	pubdate = models.DateTimeField(
		auto_now=False,
		auto_now_add=True)
	datetime = models.DateTimeField(
		verbose_name='Дата проведения',
		help_text='Введите дату в формате: дд.мм.гггг чч:мм:сс',
		auto_now=False,
		auto_now_add=False)

	class Meta:
		ordering = ['-pubdate']

psychology/events/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from events.models import Event
from django.core.paginator import Paginator
import datetime
import pytz


def events(request):
	# Часовой пояс и время для фильтра
	tz_moscow = pytz.timezone('Europe/Moscow')
	dt = datetime.datetime.now(tz_moscow)

	events = Event.objects.filter(datetime__gte=dt).order_by('datetime')
	
	per_page = 10
	page_number = request.GET.get('page')

	paginator = Paginator(events, per_page)
	page_obj = paginator.get_page(page_number)


	data = {
		'page_obj': page_obj
	}
	return render(request, 'events.html', data)


def event(request, id):
	try:
		event = Event.objects.get(id=id)
	except Event.DoesNotExist:
		return HttpResponse('404')

	data = {
		'event': event
	}

	return render(request, 'event.html', data)

psychology/users/views/lk_admin.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, resolve
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Загрузка моделей
from users.models import (
	RequestUser,
	Department,
	Skill
)

# Загрузка форм
from users.forms import (
	DepartmentForm,
	SkillForm
)

# Хелпер
from users.helpers import lk_redirect


@login_required
def list_representative(request):
	"""Список всех заявок на вступление"""
	response = lk_redirect(request)
	if response is not None:
		return response
	requests = RequestUser.objects.all()
	data = {
		'requests': requests,
		'title': 'Список заявок'
	}
	return render(request, 'users/list_requests.html', data)

@login_required
def department_add(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	form = DepartmentForm()
	if request.method == 'POST':
		form = DepartmentForm(request.POST)
		if form.is_valid():
			city = form.cleaned_data.get('city')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Город: ' + city + ' - добавлен в базу данных.')
			return HttpResponseRedirect(reverse('users:departments'))
	data = {
		'form': form,
		'title': 'Добавление города',
		'action': reverse('users:department_add'),
		'button': 'Добавить город'
	}
	return render(request, 'users/request.html', data)

@login_required
def department_edit(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Department.objects.get(id=id)
	except Department.DoesNotExist:
		return HttpResponseRedirect(reverse('users:departments'))
	form = DepartmentForm(request.POST or None, instance=obj)
	if request.method == 'POST':
		if form.is_valid():
			city = form.cleaned_data.get('city')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Город: ' + city + ' - отредактирован.')
			return HttpResponseRedirect(reverse('users:department_edit', args=[obj.id]))
	data = {
		'form': form,
		'title': 'Редактирование города',
		'action': reverse('users:department_edit'),
		'button': 'Изменить название города'
	}
	return render(request, 'users/request.html', data)

@login_required
def department_delete(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Department.objects.get(id=id)
	except Department.DoesNotExist:
		return HttpResponseRedirect(reverse('users:departments'))
	city = obj.city
	obj.delete()
	messages.add_message(
				request,
				messages.INFO,
				'Город: ' + city + ' - удалён.')
	return HttpResponseRedirect(reverse('users:departments'))

@login_required
def departments(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	departments = Department.objects.all()
	data = {
		'departments': departments,
		'title': 'Список всех городов участников'
	}
	return render(request, 'users/departments.html', data)

@login_required
def skill_add(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	form = SkillForm()
	if request.method == 'POST':
		form = SkillForm(request.POST)
		if form.is_valid():
			skill = form.cleaned_data.get('skill')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Направление: ' + skill + ' - добавлено в базу данных.')
			return HttpResponseRedirect(reverse('users:skills'))
	data = {
		'form': form,
		'title': 'Добавление специализации',
		'action': reverse('users:skill_add'),
		'button': 'Добавить навык'
	}
	return render(request, 'users/request.html', data)

@login_required
def skill_edit(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Skill.objects.get(id=id)
	except Skill.DoesNotExist:
		return HttpResponseRedirect(reverse('users:skill_edit'))
	form = SkillForm(request.POST or None, instance=obj)
	if request.method == 'POST':
		if form.is_valid():
			skill = form.cleaned_data.get('skill')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Навык: ' + skill + ' - отредактирован.')
			return HttpResponseRedirect(reverse('users:skill_edit', args=[obj.id]))
	data = {
		'form': form,
		'title': 'Редактирование навыка',
		'action': reverse('users:skill_edit', args=[obj.id]),
		'button': 'Изменить навык'
	}
	return render(request, 'users/request.html', data)

@login_required
def skill_delete(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Skill.objects.get(id=id)
	except Skill.DoesNotExist:
		return HttpResponseRedirect(reverse('users:skills'))
	skill = obj.skill
	obj.delete()
	messages.add_message(
				request,
				messages.INFO,
				'Навык: ' + skill + ' - удалён.')
	return HttpResponseRedirect(reverse('users:skills'))

@login_required
def skills(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	skills = Skill.objects.all()
	data = {
		'skills': skills,
		'title': 'Список всех направлений деятельности экспертов'
	}
	return render(request, 'users/skills.html', data)

def just(request):
	return HttpResponse(resolve(request.path))

psychology/users/views/lk_expert.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, resolve
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Загрузка моделей
from events.models import (
	Event
)

# Загрузка форм
from users.forms import (
	EventForm,
	ProfileForm
)

# Загрузка хелпера
from users.helpers import lk_redirect

@login_required
def events(request):
	"""Список всех мероприятий эксперта"""
	response = lk_redirect(request)
	if response is not None:
		return response
	events = Event.objects.filter(expert=request.user)
	data = {
		'events': events,
		'title': 'Список мероприятий'
	}
	return render(request, 'users/expert_events.html', data)


@login_required
def event_add(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	form = EventForm()
	if request.method == 'POST':
		form = EventForm(request.POST)
		if form.is_valid():
			event = form.save(commit=False)
			event.expert_id = request.user.pk
			event.save()
			messages.add_message(
				request,
				messages.INFO,
				'Мероприятие успешно добавлено!')
			return HttpResponseRedirect(reverse('users:events'))

	data = {
		'form': form,
		'title': 'Добавление мероприятия',
		'action': reverse('users:event_add'),
		'button': 'Добавить мероприятие'
	}

	return render(request, 'users/request_for_expert.html', data)

@login_required
def event_edit(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Event.objects.get(id=id)
	except Event.DoesNotExist:
		return HttpResponseRedirect(reverse('users:events'))
	if obj.expert_id != request.user.pk:
		messages.add_message(
			request,
			messages.INFO,
			'Вы не являетесь экспертом мероприятия, к которому обращаетесь')
		return HttpResponseRedirect(reverse('users:events'))
	form = EventForm(request.POST or None, instance=obj)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Мероприятие успешно отредактировано!')
			return HttpResponseRedirect(reverse('users:event_edit', args=[obj.id]))
	data = {
		'form': form,
		'title': 'Редактирование мероприятия',
		'action': reverse('users:event_edit', args=[obj.id]),
		'button': 'Внести изменения'
	}
	return render(request, 'users/request_for_expert.html', data)

@login_required
def event_delete(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Event.objects.get(id=id)
	except Event.DoesNotExist:
		return HttpResponseRedirect(reverse('users:events'))
	if obj.expert_id != request.user.pk:
		messages.add_message(
			request,
			messages.INFO,
			'Вы не являетесь экспертом мероприятия, к которому обращаетесь')
		return HttpResponseRedirect(reverse('users:events'))
	title = obj.title
	obj.delete()
	messages.add_message(
		request,
		messages.INFO,
		'Мероприятие: ' + title + ' - удалено.')
	return HttpResponseRedirect(reverse('users:events'))

@login_required
def profile(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	user = request.user
	extra_fields = user.fields
	form = ProfileForm(request.POST or None,
		files=request.FILES or None,
		instance=extra_fields)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Профиль отредактирован')
			return HttpResponseRedirect(reverse('users:profile'))
	data = {
		'form': form,
		'title': 'Редактирование профиля',
		'action': reverse('users:profile'),
		'button': 'Внести изменения',
		'files_form': True
	}
	return render(request, 'users/request_for_expert.html', data)

@login_required
def success_chg_pass(request):
	messages.add_message(
		request,
		messages.INFO,
		'Пароль успешно изменён!')
	return HttpResponseRedirect(reverse('users:expert_chg_pass'))

psychology/templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>

<!-- HEADER -->
<header class="for-header">
  {% include 'header.html' %}
</header>

<!-- NAVIGATION -->
<nav class="navbar navbar-expand-lg nav-bg">
  {% include 'nav.html' %}
</nav>

<!-- INDEX PAGE -->
<content>
  {% if messages %}
  <div class="container mb-0 mt-5">
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}
  {% block content %}
  Содержимое не найдено
  {% endblock %}
</content>

<footer>
	{% include 'footer.html' %}
</footer>

<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="https://cdn.tiny.cloud/1/m6czoyzehkvpq30cyhrxu1q6w2p9g3g5v4w7iy3dwydvvrx1/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
      tinymce.init({
        selector: 'textarea',
        plugins: 'lists',
        toolbar: 'bold italic | numlist bullist',
        menubar: false
      });
</script>
</body>
</html>

psychology/templates/event.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">

	<div class="col p-3 mb-3 bg-white border">
		<h3>
			{{ event.title }}
		</h3>
		<hr>
		<p>
			Дата проведения (МСК): 
			<span class="text-decoration-underline">
				{{ event.datetime }}
			</span>
		</p>
		<p>
			Город и адрес: 
			<span class="text-decoration-underline">
				{{ event.city }} - {{ event.address }}
			</span>
		</p>
		<p>
			Автор мероприятия: 
			<span class="text-decoration-underline">
				{{ event.expert.fields.first_name }} {{ event.expert.fields.middle_name }} 
			</span>
			-> 
			<a href="{% url 'users:expert' event.expert.id %}">Перейти в профиль</a>
		</p>
		<hr>
		<p>
			{{ event.description|safe }}
		</p>

	</div>

</div>
{% endblock %}

psychology/templates/events.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-5">
	<div class="row">
		{% if page_obj %}
		{% for event in page_obj %}
		<div class="col-12 p-3 mb-3 bg-white border">
			<h3>
				{{ event.title }}
			</h3>
			<hr>
			<p>
				Дата проведения (МСК): 
				<span class="text-decoration-underline">
					{{ event.datetime }}
				</span>
			</p>
			<p>
				Город и адрес: 
				<span class="text-decoration-underline">
					{{ event.city }} - {{ event.address }}
				</span>
			</p>
			<p>
				Автор мероприятия: 
				<span class="text-decoration-underline">
					{{ event.expert.fields.first_name }} {{ event.expert.fields.middle_name }} 
				</span>
				-> 
				<a href="{% url 'users:expert' event.expert.id %}">Перейти в профиль</a>
			</p>
			<hr>
			<p>
				{{ event.description|truncatechars_html:1000|safe }}
			</p>
			<p>
				<a href="{% url 'events:event' event.id %}">Открыть полное описание мероприятия</a>
			</p>
		</div>
		{% endfor %}
		<div class="row">
			<div class="col">
				{% include 'paginator.html' %}
			</div>
		</div>
		{% else %}
		<div class="row">
			<div class="col p-3 mb-3 bg-white border">
				<h3>Мероприятий в данный момент не проводится!</h3>
			</div>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

psychology/templates/experts.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
<div class="container mt-5 mb-2">
		{% if page_obj %}
		<div class="row row-cols-2">
		{% for expert in page_obj %}
		<!-- COL N -->
		<div class="col">

			<div class="card mb-3" style="max-width: 540px;">
				<div class="row g-0">
					<div class="col-md-4 p-2">
						{% if expert.fields.avatar %}
						{% thumbnail expert.fields.avatar "200x300" crop="center" as im %}
						<img src="{{ im.url }}" class="img-fluid" width="{{ im.width }}" height="{{ im.height }}">
						{% endthumbnail %}
						{% else %}
						<img src="https://dummyimage.com/200x300/e3e0e3/636363.jpg&text=НЕТ ФОТО" class="img-fluid" alt="...">
						{% endif %}						
					</div>
					<div class="col-md-8">
						<div class="card-body">
							<h5 class="card-title">{{ expert.fields.last_name }} {{ expert.fields.first_name }} {{ expert.fields.middle_name }}</h5>
							<hr>
							<p class="card-text">Город: {{ expert.fields.city }}</p>
							<p class="card-text">Специализация: 
							{% if expert.fields.skills.all %}
							{% for skill in expert.fields.skills.all %}
							{{ skill }}
								{% if forloop.last %}
								
								{% else %}
								-
								{% endif %}
							{% endfor %}
							{% else %}
							Не указано экспертом
							{% endif %}</p>
							<hr>
							<p class="card-text">{{ expert.fields.about|striptags|truncatechars:150 }}</p>
							<p class="card-text"><a href="{% url 'users:expert' expert.id %}">Посмотреть профиль</a></p>
						</div>
					</div>
				</div>
			</div>

		</div>
		<!-- COL N -->
		{% endfor %}
		</div>
		{% else %}
		<div class="row">
			<div class="col p-3 mb-3 bg-white border">
				<h3>Экспертов пока не зарегистрировано на портале!</h3>
			</div>
		</div>
		{% endif %}
</div>
<div class="container">
	{% include 'paginator.html' %}
</div>
{% endblock %}

psychology/templates/footer.html
<div class="container my-5 text-center">
	ИП Аникина М. О.
	ИНН 661904556373

	<br>
	<a href="{% url 'pages:oferta' %}">Договор оферты</a> | 
	<a href="{% url 'pages:confidentiality' %}">Политика конфиденциальности</a><br>
	<a href="#">Представительства</a> | 
	<a href="#">Стать представителем</a><br>
	<a href="{% url 'pages:copyright' %}">Все авторские права защищены</a> 
</div>

psychology/templates/header.html
{% load static %}
<div class="container py-2">
    <div class="row row-cols-3 align-items-center">
      <div class="col">
        <img src="{% static 'logo.jpg' %}" class="logo mx-auto d-block" />
      </div>
      <div class="col">
        <div class="s-icon">
          <a href="https://vk.com/asexpertov" target="_blank"><img src="{% static 'img/vk.png' %}" class="mx-3"></a>
          <a href="https://t.me/+4WuXzdw-s7pmN2Ey" target="_blank"><img src="{% static 'img/tg.png' %}" class="mx-3"></a>
          <a href="mailto:a.expertov@yandex.ru" target="_blank"><img src="{% static 'img/mail.png' %}" class="mx-3"></a>
        </div>
      </div>
      <div class="col justify-content-center">
          <a href="{% url 'users:get_representative' %}" class="btn btn-primary">Вступить в ассоциацию</a>
      </div>
    </div>
  </div>

psychology/templates/lk_admin.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ title }}</title>
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
</head>
<body>

<!-- HEADER -->
<header class="for-header">
  {% include 'header.html' %}
</header>

<!-- NAVIGATION -->
<nav class="navbar navbar-expand-lg nav-bg">
  {% include 'nav_admin.html' %}
</nav>

<!-- INDEX PAGE -->
<content>
  {% if messages %}
  <div class="container mb-0 mt-5">
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}



  {% block content %}
  Содержимое не найдено
  {% endblock %}
</content>

<footer>
	{% include 'footer.html' %}
</footer>

<script src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>

psychology/templates/nav.html
<div class="container">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav top-menu">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:index' %}">Ассоциация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:experts' %}">Сообщество экспертов</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'events:events' %}">Мероприятия</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">ЛК</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">{{ request.user }}</a>
        </li>
        {% endif %}
      </ul>
    </div>

  </div>

psychology/templates/nav_admin.html
<div class="container">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav top-menu">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:index' %}">Перейти на сайт</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:list_representative' %}">Список заявок</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:departments' %}">Список городов</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:skills' %}">Список направлений</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li>
      </ul>
    </div>

  </div>

psychology/templates/nav_expert.html
<div class="container">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav top-menu">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:index' %}">Перейти на сайт</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:events' %}">Мероприятия</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:expert_chg_pass' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li>
      </ul>
    </div>

  </div>