psychology/pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'

urlpatterns = [
	path('', views.index, name='index'),
	path('oferta/', views.oferta, name='oferta'),
	path('confidentiality/', views.confidentiality, name='confidentiality'),
	path('copyright/', views.copyright, name='copyright'),
	path('representative/', views.representative, name='representative')
]

psychology/psychology/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('users/', include('users.urls', namespace='users')),
    path('events/', include('events.urls', namespace='events')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

psychology/users/urls.py
from django.urls import path
from users.views import (
	views,
	lk_admin,
	lk_expert
)
from django.contrib.auth import views as a_views
from users.forms import (
	YourOwnChangePassForm,
	YourOwnResetPassForm,
	YourOwnSetPassForm
)

app_name = 'users'

urlpatterns = [
	# Авторизация
	path('get_representative/',
		views.get_representative,
		name='get_representative'),
	path('invite/<int:id>/',
		views.invite,
		name='invite'),
	path('reg/<str:link>',
		views.registration,
		name='registration'),
	path('login/',
		views.login_view,
		name='login'),
	path('logout/',
		views.logout_view,
		name='logout'),
	path('password_reset/',
		a_views.PasswordResetView.as_view(
			template_name='users/reset_password_form.html',
			form_class=YourOwnResetPassForm,
			success_url='done',
			email_template_name='emails/password_reset_email.html'),
		name='reset_pass'),
	path('password_reset/done/',
		views.reset_pass_done,
		name='reset_pass_done'),
	path('reset/<uidb64>/<token>/',
		a_views.PasswordResetConfirmView.as_view(
			template_name='users/reset_password_form.html',
			form_class=YourOwnSetPassForm,
			success_url='done/'),
		name='password_reset_confirm'),
	path('reset/<uidb64>/set-password/done/',
		views.pass_confirm_done,
		name='confirm_pass_done'),

	# Личный кабинет администратора
	path('list_representative/',
		lk_admin.list_representative,
		name='list_representative'),

	path('department/add/',
		lk_admin.department_add,
		name='department_add'),
	path('department/edit/<int:id>/',
		lk_admin.department_edit,
		name='department_edit'),
	path('department/delete/<int:id>/',
		lk_admin.department_delete,
		name='department_delete'),
	path('departments/',
		lk_admin.departments,
		name='departments'),

	path('skill/add/',
		lk_admin.skill_add,
		name='skill_add'),
	path('skill/edit/<int:id>/',
		lk_admin.skill_edit,
		name='skill_edit'),
	path('skill/delete/<int:id>/',
		lk_admin.skill_delete,
		name='skill_delete'),
	path('skills/',
		lk_admin.skills,
		name='skills'),
	path('just/',
		lk_admin.just,
		name='just12'),

	# Личный кабинет эксперта
	path('events/',
		lk_expert.events,
		name='events'),
	path('events/add/',
		lk_expert.event_add,
		name='event_add'),
	path('events/edit/<int:id>/',
		lk_expert.event_edit,
		name='event_edit'),
	path('events/delete/<int:id>/',
		lk_expert.event_delete,
		name='event_delete'),

	path('profile/',
		lk_expert.profile,
		name='profile'),
	path('expert_chg_pass/',
		a_views.PasswordChangeView.as_view(
			template_name='users/chg_pass_expert.html',
			form_class=YourOwnChangePassForm,
			success_url='done'),
		name='expert_chg_pass'),
	path('expert_chg_pass/done/',
		lk_expert.success_chg_pass,
		name='success_chg_pass'),

	path('', views.experts, name='experts'),
	path('id/<int:id>/', views.expert, name='expert')
]

psychology/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
import hashlib

# Загрузка моделей
from .models import (
	RequestUser,
	Invite
)

# Загрузка форм
from .forms import RequestUserForm


def get_representative(request):
	"""Форма для отправки запроса на вступление в ассоциацию"""
	form = RequestUserForm()

	if request.method == 'POST':
		form = RequestUserForm(request.POST)
		if form.is_valid():
			obj = RequestUser(**form.cleaned_data)
			obj.save()
			return HttpResponseRedirect('/users/list_representative')

	data = {
		'form': form,
		'title': 'Заявка на вступление в Ассоциацию'
	}

	return render(request, 'users/request.html', data)


def list_representative(request):
	"""Список всех заявок на вступление"""
	requests = RequestUser.objects.all()
	data = {
		'requests': requests,
		'title': 'Список заявок'
	}
	return render(request, 'users/list_requests.html', data)


def invite(request, id):
	"""
	Отправка приглашения на почтовый адрес
	1.	Формируется уникальная строка
	2.	Строка добавляется в базу и отправляется
		пользователю по Email
	3.	Строка формируется из Имени, Фамилии
	"""
	try:
		obj = RequestUser.objects.get(id=id)
	except RequestUser.DoesNotExist:
		return HttpResponse('404')

	link_to_invite = obj.last_name + obj.first_name
	hash_link = hashlib.new('md5')
	hash_link.update(link_to_invite.encode())
	hash_link = hash_link.hexdigest()

	invite = Invite.objects.get_or_create(
		request=obj,
		link=hash_link
	)

	send_mail(
		'[aaxpert] Приглашение на регистрацию',
		'Ваш HASH для вступления: http://s.com/check/' + hash_link,
		'from@mailer.com',
		['to@mailer.com'],
		fail_silently=False
	)
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

psychology/users/views/lk_admin.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, resolve
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Загрузка моделей
from users.models import (
	RequestUser,
	Department,
	Skill
)

# Загрузка форм
from users.forms import (
	DepartmentForm,
	SkillForm
)

# Хелпер
from users.helpers import lk_redirect


@login_required
def list_representative(request):
	"""Список всех заявок на вступление"""
	response = lk_redirect(request)
	if response is not None:
		return response
	requests = RequestUser.objects.all()
	data = {
		'requests': requests,
		'title': 'Список заявок'
	}
	return render(request, 'users/list_requests.html', data)

@login_required
def department_add(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	form = DepartmentForm()
	if request.method == 'POST':
		form = DepartmentForm(request.POST)
		if form.is_valid():
			city = form.cleaned_data.get('city')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Город: ' + city + ' - добавлен в базу данных.')
			return HttpResponseRedirect(reverse('users:departments'))
	data = {
		'form': form,
		'title': 'Добавление города',
		'action': reverse('users:department_add'),
		'button': 'Добавить город'
	}
	return render(request, 'users/request.html', data)

@login_required
def department_edit(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Department.objects.get(id=id)
	except Department.DoesNotExist:
		return HttpResponseRedirect(reverse('users:departments'))
	form = DepartmentForm(request.POST or None, instance=obj)
	if request.method == 'POST':
		if form.is_valid():
			city = form.cleaned_data.get('city')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Город: ' + city + ' - отредактирован.')
			return HttpResponseRedirect(reverse('users:department_edit', args=[obj.id]))
	data = {
		'form': form,
		'title': 'Редактирование города',
		'action': reverse('users:department_edit'),
		'button': 'Изменить название города'
	}
	return render(request, 'users/request.html', data)

@login_required
def department_delete(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Department.objects.get(id=id)
	except Department.DoesNotExist:
		return HttpResponseRedirect(reverse('users:departments'))
	city = obj.city
	obj.delete()
	messages.add_message(
				request,
				messages.INFO,
				'Город: ' + city + ' - удалён.')
	return HttpResponseRedirect(reverse('users:departments'))

@login_required
def departments(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	departments = Department.objects.all()
	data = {
		'departments': departments,
		'title': 'Список всех городов участников'
	}
	return render(request, 'users/departments.html', data)

@login_required
def skill_add(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	form = SkillForm()
	if request.method == 'POST':
		form = SkillForm(request.POST)
		if form.is_valid():
			skill = form.cleaned_data.get('skill')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Направление: ' + skill + ' - добавлено в базу данных.')
			return HttpResponseRedirect(reverse('users:skills'))
	data = {
		'form': form,
		'title': 'Добавление специализации',
		'action': reverse('users:skill_add'),
		'button': 'Добавить навык'
	}
	return render(request, 'users/request.html', data)

@login_required
def skill_edit(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Skill.objects.get(id=id)
	except Skill.DoesNotExist:
		return HttpResponseRedirect(reverse('users:skill_edit'))
	form = SkillForm(request.POST or None, instance=obj)
	if request.method == 'POST':
		if form.is_valid():
			skill = form.cleaned_data.get('skill')
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Навык: ' + skill + ' - отредактирован.')
			return HttpResponseRedirect(reverse('users:skill_edit', args=[obj.id]))
	data = {
		'form': form,
		'title': 'Редактирование навыка',
		'action': reverse('users:skill_edit', args=[obj.id]),
		'button': 'Изменить навык'
	}
	return render(request, 'users/request.html', data)

@login_required
def skill_delete(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Skill.objects.get(id=id)
	except Skill.DoesNotExist:
		return HttpResponseRedirect(reverse('users:skills'))
	skill = obj.skill
	obj.delete()
	messages.add_message(
				request,
				messages.INFO,
				'Навык: ' + skill + ' - удалён.')
	return HttpResponseRedirect(reverse('users:skills'))

@login_required
def skills(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	skills = Skill.objects.all()
	data = {
		'skills': skills,
		'title': 'Список всех направлений деятельности экспертов'
	}
	return render(request, 'users/skills.html', data)

def just(request):
	return HttpResponse(resolve(request.path))

psychology/users/views/lk_expert.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, resolve
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Загрузка моделей
from events.models import (
	Event
)

# Загрузка форм
from users.forms import (
	EventForm,
	ProfileForm
)

# Загрузка хелпера
from users.helpers import lk_redirect

@login_required
def events(request):
	"""Список всех мероприятий эксперта"""
	response = lk_redirect(request)
	if response is not None:
		return response
	events = Event.objects.filter(expert=request.user)
	data = {
		'events': events,
		'title': 'Список мероприятий'
	}
	return render(request, 'users/expert_events.html', data)


@login_required
def event_add(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	form = EventForm()
	if request.method == 'POST':
		form = EventForm(request.POST)
		if form.is_valid():
			event = form.save(commit=False)
			event.expert_id = request.user.pk
			event.save()
			messages.add_message(
				request,
				messages.INFO,
				'Мероприятие успешно добавлено!')
			return HttpResponseRedirect(reverse('users:events'))

	data = {
		'form': form,
		'title': 'Добавление мероприятия',
		'action': reverse('users:event_add'),
		'button': 'Добавить мероприятие'
	}

	return render(request, 'users/request_for_expert.html', data)

@login_required
def event_edit(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Event.objects.get(id=id)
	except Event.DoesNotExist:
		return HttpResponseRedirect(reverse('users:events'))
	if obj.expert_id != request.user.pk:
		messages.add_message(
			request,
			messages.INFO,
			'Вы не являетесь экспертом мероприятия, к которому обращаетесь')
		return HttpResponseRedirect(reverse('users:events'))
	form = EventForm(request.POST or None, instance=obj)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Мероприятие успешно отредактировано!')
			return HttpResponseRedirect(reverse('users:event_edit', args=[obj.id]))
	data = {
		'form': form,
		'title': 'Редактирование мероприятия',
		'action': reverse('users:event_edit', args=[obj.id]),
		'button': 'Внести изменения'
	}
	return render(request, 'users/request_for_expert.html', data)

@login_required
def event_delete(request, id):
	response = lk_redirect(request)
	if response is not None:
		return response
	try:
		obj = Event.objects.get(id=id)
	except Event.DoesNotExist:
		return HttpResponseRedirect(reverse('users:events'))
	if obj.expert_id != request.user.pk:
		messages.add_message(
			request,
			messages.INFO,
			'Вы не являетесь экспертом мероприятия, к которому обращаетесь')
		return HttpResponseRedirect(reverse('users:events'))
	title = obj.title
	obj.delete()
	messages.add_message(
		request,
		messages.INFO,
		'Мероприятие: ' + title + ' - удалено.')
	return HttpResponseRedirect(reverse('users:events'))

@login_required
def profile(request):
	response = lk_redirect(request)
	if response is not None:
		return response
	user = request.user
	extra_fields = user.fields
	form = ProfileForm(request.POST or None,
		files=request.FILES or None,
		instance=extra_fields)
	if request.method == 'POST':
		if form.is_valid():
			form.save()
			messages.add_message(
				request,
				messages.INFO,
				'Профиль отредактирован')
			return HttpResponseRedirect(reverse('users:profile'))
	data = {
		'form': form,
		'title': 'Редактирование профиля',
		'action': reverse('users:profile'),
		'button': 'Внести изменения',
		'files_form': True
	}
	return render(request, 'users/request_for_expert.html', data)

@login_required
def success_chg_pass(request):
	messages.add_message(
		request,
		messages.INFO,
		'Пароль успешно изменён!')
	return HttpResponseRedirect(reverse('users:expert_chg_pass'))

psychology/templates/users/chg_pass_expert.html
{% extends 'lk_expert.html' %}


{% block content %}
<div class="container my-5">

	<div class="card">
		<div class="card-header">
			Смена пароля
		</div>
		<div class="card-body">
			{% if form.errors %}
			{% for error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ error|escape }}
			</div>
			{% endfor %}

			{% endif %}
			<form novalidate method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="row my-2 py-2 align-items-center border-bottom">
					<div class="col-4 text-center">
						<label class="form-label" id="{{ field.id_for_label }}">{{ field.label }}</label>
					</div>
					<div class="col-8">
						{{ field }}
						{% if field.errors %}
							{% for error in field.errors %}
							<div class="form-text text-danger">{{ error|escape }}</div>
							{% endfor %}
						{% endif %}
						<p></p>
						{% if field.help_text %}
						<div class="form-text">{{ field.help_text }}</div>
						{% endif %}
					</div>
				</div>
				{% endfor %}
				<div class="row my-2 py-2">
					<div class="col text-center">
						<button type="submit" class="btn btn-primary">Сменить пароль</button>
					</div>
					
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

psychology/templates/users/departments.html
{% extends 'lk_admin.html' %}

{% block content %}
<div class="container my-5">
	<div class="card">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			<p>Чтобы добавить город, перейдите по ссылке: <a href="{% url 'users:department_add' %}">Добавить город</a></p>
			<table class="table table-bordered table-hover table-stripped">
				<thead>
					<tr class="table-dark">
						<td class="col-1">ID</td>
						<td class="col-7">Город</td>
						<td class="col-4"></td>
					</tr>
				</thead>
				<tbody>
					{% for d in departments %}
					<tr>
						<td>{{ d.id }}</td>
						<td>{{ d.city }}</td>
						<td><a href="{% url 'users:department_edit' d.id %}">Редактировать</a> | <a href="{% url 'users:department_delete' d.id %}">Удалить</a></td>
					</tr>
					{% endfor %}
				</tbody>

			</table>
		</div>
	</div>
	
</div>
{% endblock %}

psychology/templates/users/expert_events.html
{% extends 'lk_expert.html' %}

{% block content %}
<div class="container my-5">
	<div class="card">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			<p>Чтобы добавить мероприятие, перейдите по ссылке: <a href="{% url 'users:event_add' %}">Добавить мероприятие</a></p>
			<table class="table table-bordered table-hover table-stripped">
				<thead>
					<tr class="table-dark">
						<td class="col-5">Название</td>
						<td class="col-3">Город</td>
						<td class="col-3">Дата проведения</td>
						<td class="col-1"></td>
					</tr>
				</thead>
				<tbody>
					{% for e in events %}
					<tr>
						<td>{{ e.title }}</td>
						<td>{{ e.city.city }}</td>
						<td>{{ e.datetime }}</td>
						<td><a href="{% url 'users:event_edit' e.id %}" title="Редактировать мероприятие">Р</a> | <a href="{% url 'users:event_delete' e.id %}" title="Удалить мероприятие">У</a></td>
					</tr>
					{% endfor %}
				</tbody>

			</table>
		</div>
	</div>
	
</div>
{% endblock %}

psychology/templates/users/list_requests.html
{% extends 'lk_admin.html' %}

{% block content %}
<div class="container my-5">
	<div class="card">
		<div class="card-header">
			Список заявок на вступление в Ассоциацию
		</div>
		<div class="card-body">
			<p>Желтым цветом подсвечиваются заявки, по которым прошла регистрация на портале. Голубым цветом подсвечиваются заявки, по которым было выслано приглашение на почту. Не подсвечиваются остальные заявки.</p>
			<table class="table table-bordered table-hover table-stripped">
				<thead>
					<tr class="table-dark">
						<td>ID</td>
						<td>Фамилия</td>
						<td>Имя</td>
						<td>Телефон</td>
						<td>Город</td>
						<td>Специализация</td>
						<td>Отправить приглашение?</td>
					</tr>
				</thead>
				<tbody>
					{% for r in requests %}
					<tr {% if r.invite %}

							{% if r.invite.status %}
								class="table-warning"
							{% else %}
								class="table-info"
							{% endif %}

					{% endif %}>
						<td>{{ r.id }}</td>
						<td>{{ r.last_name }}</td>
						<td>{{ r.first_name }}</td>
						<td>{{ r.phone }}</td>
						<td>{{ r.city }}</td>
						<td>{{ r.skill }}</td>
						<td>
							{% if r.invite %}
								{% if r.invite.status %}
								Зарегистрировался...
								{% else %}
								<a href="{% url 'users:invite' r.id %}">Пригласить повторно</a>
								{% endif %}
							{% else %}
							<a href="{% url 'users:invite' r.id %}">Выслать приглашение</a>
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</tbody>

			</table>
		</div>
	</div>
	
</div>
{% endblock %}

psychology/templates/users/login.html
{% extends 'base.html' %}


{% block content %}
<div class="container my-5">

	<div class="card">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			{% if form.errors %}
			{% for error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ error|escape }}
			</div>
			{% endfor %}

			{% endif %}
			<form novalidate action="{{ action }}" method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="row my-2 py-2 align-items-center border-bottom">
					<div class="col-4 text-center">
						<label class="form-label" id="{{ field.id_for_label }}">{{ field.label }}</label>
					</div>
					<div class="col-8">
						{{ field }}
						{% if field.errors %}
							{% for error in field.errors %}
							<div class="form-text text-danger">{{ error|escape }}</div>
							{% endfor %}
						{% endif %}
						{% if field.help_text %}
						<div class="form-text">{{ field.help_text }}</div>
						{% endif %}
					</div>
				</div>
				{% endfor %}
				<div class="row my-2 py-2">
					<div class="col text-center">
						<button type="submit" class="btn btn-primary">{{ button }}</button>
					</div>
					
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

psychology/templates/users/request.html
{% extends 'lk_admin.html' %}


{% block content %}
<div class="container my-5">

	<div class="card">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			{% if form.errors %}
			{% for error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ error|escape }}
			</div>
			{% endfor %}

			{% endif %}
			<form novalidate action="{{ action }}" method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="row my-2 py-2 align-items-center border-bottom">
					<div class="col-4 text-center">
						<label class="form-label" id="{{ field.id_for_label }}">{{ field.label }}</label>
					</div>
					<div class="col-8">
						{{ field }}
						{% if field.errors %}
							{% for error in field.errors %}
							<div class="form-text text-danger">{{ error|escape }}</div>
							{% endfor %}
						{% endif %}
						{% if field.help_text %}
						<div class="form-text">{{ field.help_text }}</div>
						{% endif %}
					</div>
				</div>
				{% endfor %}
				<div class="row my-2 py-2">
					<div class="col text-center">
						<button type="submit" class="btn btn-primary">{{ button }}</button>
					</div>
					
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

psychology/templates/users/request_for_base.html
{% extends 'base.html' %}


{% block content %}
<div class="container my-5">

	<div class="card">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			{% if form.errors %}
			{% for error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ error|escape }}
			</div>
			{% endfor %}

			{% endif %}
			<form novalidate action="{{ action }}" method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="row my-2 py-2 align-items-center border-bottom">
					<div class="col-4 text-center">
						<label class="form-label" id="{{ field.id_for_label }}">{{ field.label }}</label>
					</div>
					<div class="col-8">
						{{ field }}
						{% if field.errors %}
							{% for error in field.errors %}
							<div class="form-text text-danger">{{ error|escape }}</div>
							{% endfor %}
						{% endif %}
						{% if field.help_text %}
						<div class="form-text">{{ field.help_text }}</div>
						{% endif %}
					</div>
				</div>
				{% endfor %}
				<div class="row my-2 py-2">
					<div class="col text-center">
						<button type="submit" class="btn btn-primary">{{ button }}</button>
					</div>
					
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

psychology/templates/users/request_for_skills.html
{% extends 'lk_expert.html' %}


{% block content %}
<div class="container my-5">

	<div class="card mb-3">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			{% if form.errors %}
			{% for error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				{{ error|escape }}
			</div>
			{% endfor %}

			{% endif %}
			<form novalidate
			{% if files_form %}
			enctype="multipart/form-data"
			{% endif %}
			action="{{ action }}" method="post">
				{% csrf_token %}
				{% for field in form %}
				<div class="row my-2 py-2 align-items-center border-bottom">
					<div class="col-4 text-center">
						<label class="form-label" id="{{ field.id_for_label }}">{{ field.label }}</label>
					</div>
					<div class="col-8">
						{{ field }}
						{% if field.errors %}
							{% for error in field.errors %}
							<div class="form-text text-danger">{{ error|escape }}</div>
							{% endfor %}
						{% endif %}
						{% if field.help_text %}
						<div class="form-text">{{ field.help_text }}</div>
						{% endif %}
					</div>
				</div>
				{% endfor %}
				<div class="row my-2 py-2">
					<div class="col text-center">
						<button type="submit" class="btn btn-primary">{{ button }}</button>
					</div>
					
				</div>
			</form>
		</div>
	</div>

	<div class="card">
		<div class="card-header">
			Список Ваших специализаций
		</div>
		<div class="card-body">
			<p>Управление Вашими навыками.</p>
			<table class="table table-bordered table-hover table-stripped">
				<thead>
					<tr class="table-dark">
						<td class="col-1">ID</td>
						<td class="col-7">Навык</td>
						<td class="col-4"></td>
					</tr>
				</thead>
				<tbody>
					{% for s in skills %}
					<tr>
						<td>{{ s.id }}</td>
						<td>{{ s.city }}</td>
						<td><a href="{% url 'users:department_edit' s.id %}">Редактировать</a> | <a href="{% url 'users:department_delete' s.id %}">Удалить</a></td>
					</tr>
					{% endfor %}
				</tbody>

			</table>
		</div>
	</div>
</div>
{% endblock %}

psychology/templates/users/skills.html
{% extends 'lk_admin.html' %}

{% block content %}
<div class="container my-5">
	<div class="card">
		<div class="card-header">
			{{ title }}
		</div>
		<div class="card-body">
			<p>Чтобы добавить навык, перейдите по ссылке: <a href="{% url 'users:skill_add' %}">Добавить навык</a></p>
			<table class="table table-bordered table-hover table-stripped">
				<thead>
					<tr class="table-dark">
						<td class="col-1">ID</td>
						<td class="col-7">Навык</td>
						<td class="col-4"></td>
					</tr>
				</thead>
				<tbody>
					{% for s in skills %}
					<tr>
						<td>{{ s.id }}</td>
						<td>{{ s.skill }}</td>
						<td><a href="{% url 'users:skill_edit' s.id %}">Редактировать</a> | <a href="{% url 'users:skill_delete' s.id %}">Удалить</a></td>
					</tr>
					{% endfor %}
				</tbody>

			</table>
		</div>
	</div>
	
</div>
{% endblock %}